[build]
cmd = "go build -o ./tmp/api ./go/lambda/api/"
bin = "./tmp/api"
full_bin = "AWS_PROFILE=ktp ./tmp/api 2>&1 | tee ./tmp/api.log"
watch_dir = "go"
include_ext = ["go"]
exclude_dir = ["tmp", "site", "aws", "node_modules"]
delay = 500

[log]
time = false

[misc]
clean_on_exit = true
